PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT DISTINCT ?disjointClass {
  # Check for both directions (it's reflexive).
  # DISTINCT to avoid duplication in case both directions are asserted in input. 
  {
    ?term owl:disjointWith ?disjointClass
  } UNION {
    ?disjointClass owl:disjointWith ?term
  }
  FILTER (isURI(?disjointClass))
}